apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/victoria-metrics-stack
  - ../../base/fluent-bit

configMapGenerator:
  - name: victoria-dev-values
    files:
      - values.yaml=values-dev.yaml

generatorOptions:
  disableNameSuffixHash: true
