apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.9.19
    releaseName: victoriametrics
    namespace: observability
    valuesFile: values.yaml

namespace: observability
